const places: google.maps.places.PlaceResult[] = [
    {
        place_id: "1",
        name: "Union Oyster House",
        geometry: { location: { lat: 42.361247, lng: -71.056998 }, viewport: null },
        rating: 4.4,
        types: ["restaurant", "food", "point_of_interest", "establishment"],
    },
    {
        place_id: "2",
        name: "The Bell in Hand Tavern",
        geometry: { location: { lat: 42.361852, lng: -71.057709 }, viewport: null },
        rating: 4.3,
        types: ["bar", "food", "point_of_interest", "establishment"],
    },
    {
        place_id: "3",
        name: "Faneuil Hall Marketplace",
        geometry: { location: { lat: 42.360003, lng: -71.056993 }, viewport: null },
        rating: 4.5,
        types: ["tourist_attraction", "point_of_interest", "establishment"],
    },
    {
        place_id: "4",
        name: "Cheers Boston",
        geometry: { location: { lat: 42.355317, lng: -71.071086 }, viewport: null },
        rating: 4.2,
        types: ["bar", "restaurant", "point_of_interest", "establishment"],
    },
    {
        place_id: "5",
        name: "Boston Common",
        geometry: { location: { lat: 42.355438, lng: -71.065693 }, viewport: null },
        rating: 4.7,
        types: ["park", "point_of_interest", "establishment"],
    },
    {
        place_id: "6",
        name: "Legal Sea Foods - Long Wharf",
        geometry: { location: { lat: 42.359426, lng: -71.049934 }, viewport: null },
        rating: 4.4,
        types: ["restaurant", "food", "point_of_interest", "establishment"],
    },
    {
        place_id: "7",
        name: "Neptune Oyster",
        geometry: { location: { lat: 42.363918, lng: -71.054873 }, viewport: null },
        rating: 4.6,
        types: ["restaurant", "food", "point_of_interest", "establishment"],
    },
    {
        place_id: "8",
        name: "Parker's Restaurant",
        geometry: { location: { lat: 42.357455, lng: -71.058259 }, viewport: null },
        rating: 4.3,
        types: ["restaurant", "food", "point_of_interest", "establishment"],
    },
    {
        place_id: "9",
        name: "Lolita Cocina & Tequila Bar Back Bay",
        geometry: { location: { lat: 42.351212, lng: -71.073435 }, viewport: null },
        rating: 4.4,
        types: ["bar", "restaurant", "point_of_interest", "establishment"],
    },
    {
        place_id: "10",
        name: "Top of the Hub",
        geometry: { location: { lat: 42.347595, lng: -71.082502 }, viewport: null },
        rating: 4.3,
        types: ["restaurant", "bar", "point_of_interest", "establishment"],
    },
    {
        place_id: "11",
        name: "Fenway Park",
        geometry: { location: { lat: 42.346676, lng: -71.097218 }, viewport: null },
        rating: 4.8,
        types: ["stadium", "tourist_attraction", "point_of_interest", "establishment"],
    },
    {
        place_id: "12",
        name: "Boston Tea Party Ships & Museum",
        geometry: { location: { lat: 42.352251, lng: -71.050514 }, viewport: null },
        rating: 4.6,
        types: ["museum", "point_of_interest", "establishment"],
    },
    {
        place_id: "13",
        name: "The Barking Crab",
        geometry: { location: { lat: 42.351564, lng: -71.046525 }, viewport: null },
        rating: 4.2,
        types: ["restaurant", "food", "point_of_interest", "establishment"],
    },
    {
        place_id: "14",
        name: "Trillium Brewing Company - Fort Point",
        geometry: { location: { lat: 42.351158, lng: -71.049438 }, viewport: null },
        rating: 4.7,
        types: ["bar", "brewery", "point_of_interest", "establishment"],
    },
    {
        place_id: "15",
        name: "Old North Church",
        geometry: { location: { lat: 42.366291, lng: -71.054412 }, viewport: null },
        rating: 4.7,
        types: ["church", "tourist_attraction", "point_of_interest", "establishment"],
    },
    {
        place_id: "16",
        name: "The Warren Tavern",
        geometry: { location: { lat: 42.376203, lng: -71.062118 }, viewport: null },
        rating: 4.5,
        types: ["restaurant", "bar", "point_of_interest", "establishment"],
    },
    {
        place_id: "17",
        name: "Sam Adams Brewery",
        geometry: { location: { lat: 42.314104, lng: -71.103766 }, viewport: null },
        rating: 4.6,
        types: ["brewery", "point_of_interest", "establishment"],
    },
    {
        place_id: "18",
        name: "Mike's Pastry",
        geometry: { location: { lat: 42.363654, lng: -71.054888 }, viewport: null },
        rating: 4.5,
        types: ["bakery", "food", "point_of_interest", "establishment"],
    },
    {
        place_id: "19",
        name: "The Envoy Hotel Rooftop Bar",
        geometry: { location: { lat: 42.352796, lng: -71.047034 }, viewport: null },
        rating: 4.3,
        types: ["bar", "point_of_interest", "establishment"],
    },
    {
        place_id: "20",
        name: "Harpoon Brewery & Beer Hall",
        geometry: { location: { lat: 42.348865, lng: -71.034424 }, viewport: null },
        rating: 4.7,
        types: ["brewery", "bar", "point_of_interest", "establishment"],
    },
];
